### ISSUE TITLE
Make a changelog for v3

### ISSUE THREAD

**Issue by m93a** [m93a/filtrex#49]
Version 3 brings a lot of changes, including breaking ones. Either a readme or a wiki page should include a complete changelog. Furthermore, make sure that each new feature is properly documented in the readme.

**BREAKING DESIGN CHANGES:**
 * [x] #22 (Returning runtime errors instead of `undefined`.)
 * [x] #27 (Not converting booleans to numbers anymore.)
 * [x] #36 (Modulo can no more return a negative result.)
 * [x] #47
 
**BREAKING BUG FIXES:**
 * [x] #41
 * [x] #42 (Changed `not in` to have the same precedence as `in`.)
 * [x] #43 (Changed exponentiation to be right-associative.)
 
**DEPRECATIONS:**
 * [x] #34 (Ternary `? :` operator deprecated in favor of `if then else`.)
 * [x] #48 (`%` deprecated in favor of `mod`.)

**NEW FEATURES:**
 * [x] #30
 * [x] #35
 * [x] #37
 * [x] #38
 * [x] #44 (Optional chaining and dot accessor syntax.)
 * [x] `customProp` now has additional argument `type: 'unescaped' | 'single-quoted'`
